<?php
/**
 * ContactDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * ContactDtoTest Class Doc Comment
 *
 * @category    Class
 * @description This class represents a contact in ContactController. Used by getting data.
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContactDto"
     */
    public function testContactDto()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {
    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {
    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {
    }

    /**
     * Test attribute "position"
     */
    public function testPropertyPosition()
    {
    }

    /**
     * Test attribute "business_account"
     */
    public function testPropertyBusinessAccount()
    {
    }

    /**
     * Test attribute "business_account_type"
     */
    public function testPropertyBusinessAccountType()
    {
    }

    /**
     * Test attribute "same_as_account"
     */
    public function testPropertySameAsAccount()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "web"
     */
    public function testPropertyWeb()
    {
    }

    /**
     * Test attribute "phone1"
     */
    public function testPropertyPhone1()
    {
    }

    /**
     * Test attribute "phone2"
     */
    public function testPropertyPhone2()
    {
    }

    /**
     * Test attribute "phone3"
     */
    public function testPropertyPhone3()
    {
    }

    /**
     * Test attribute "fax"
     */
    public function testPropertyFax()
    {
    }

    /**
     * Test attribute "contact_method"
     */
    public function testPropertyContactMethod()
    {
    }

    /**
     * Test attribute "do_not_call"
     */
    public function testPropertyDoNotCall()
    {
    }

    /**
     * Test attribute "do_not_fax"
     */
    public function testPropertyDoNotFax()
    {
    }

    /**
     * Test attribute "do_not_email"
     */
    public function testPropertyDoNotEmail()
    {
    }

    /**
     * Test attribute "do_not_mail"
     */
    public function testPropertyDoNotMail()
    {
    }

    /**
     * Test attribute "no_mass_mail"
     */
    public function testPropertyNoMassMail()
    {
    }

    /**
     * Test attribute "no_marketing"
     */
    public function testPropertyNoMarketing()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }

    /**
     * Test attribute "contact_id"
     */
    public function testPropertyContactId()
    {
    }
}
