<?php
/**
 * JournalTransactionLineDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * JournalTransactionLineDtoTest Class Doc Comment
 *
 * @category    Class
 * @description JournalTransactionLineDto
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JournalTransactionLineDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "JournalTransactionLineDto"
     */
    public function testJournalTransactionLineDto()
    {
    }

    /**
     * Test attribute "line_number"
     */
    public function testPropertyLineNumber()
    {
    }

    /**
     * Test attribute "account_number"
     */
    public function testPropertyAccountNumber()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "subaccount"
     */
    public function testPropertySubaccount()
    {
    }

    /**
     * Test attribute "reference_number"
     */
    public function testPropertyReferenceNumber()
    {
    }

    /**
     * Test attribute "debit_amount"
     */
    public function testPropertyDebitAmount()
    {
    }

    /**
     * Test attribute "debit_amount_in_currency"
     */
    public function testPropertyDebitAmountInCurrency()
    {
    }

    /**
     * Test attribute "credit_amount"
     */
    public function testPropertyCreditAmount()
    {
    }

    /**
     * Test attribute "credit_amount_in_currency"
     */
    public function testPropertyCreditAmountInCurrency()
    {
    }

    /**
     * Test attribute "transaction_description"
     */
    public function testPropertyTransactionDescription()
    {
    }

    /**
     * Test attribute "vat_code"
     */
    public function testPropertyVatCode()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "customer_supplier"
     */
    public function testPropertyCustomerSupplier()
    {
    }

    /**
     * Test attribute "transaction_type"
     */
    public function testPropertyTransactionType()
    {
    }

    /**
     * Test attribute "module"
     */
    public function testPropertyModule()
    {
    }

    /**
     * Test attribute "uom"
     */
    public function testPropertyUom()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "project_task"
     */
    public function testPropertyProjectTask()
    {
    }

    /**
     * Test attribute "attachments"
     */
    public function testPropertyAttachments()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "inventory_number"
     */
    public function testPropertyInventoryNumber()
    {
    }
}
