<?php
/**
 * KitSpecificationDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * KitSpecificationDtoTest Class Doc Comment
 *
 * @category    Class
 * @description KitSpecificationDto
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KitSpecificationDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "KitSpecificationDto"
     */
    public function testKitSpecificationDto()
    {
    }

    /**
     * Test attribute "kit_inventory_id"
     */
    public function testPropertyKitInventoryId()
    {
    }

    /**
     * Test attribute "revision"
     */
    public function testPropertyRevision()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "is_active"
     */
    public function testPropertyIsActive()
    {
    }

    /**
     * Test attribute "allow_component_addition"
     */
    public function testPropertyAllowComponentAddition()
    {
    }

    /**
     * Test attribute "is_non_stock"
     */
    public function testPropertyIsNonStock()
    {
    }

    /**
     * Test attribute "stock_component_lines"
     */
    public function testPropertyStockComponentLines()
    {
    }

    /**
     * Test attribute "non_stock_component_lines"
     */
    public function testPropertyNonStockComponentLines()
    {
    }

    /**
     * Test attribute "error_info"
     */
    public function testPropertyErrorInfo()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
