<?php
/**
 * ProjectTransactionLineDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * ProjectTransactionLineDtoTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectTransactionLineDto
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectTransactionLineDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectTransactionLineDto"
     */
    public function testProjectTransactionLineDto()
    {
    }

    /**
     * Test attribute "tran_id"
     */
    public function testPropertyTranId()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "inventory_id"
     */
    public function testPropertyInventoryId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "uom"
     */
    public function testPropertyUom()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unit_rate"
     */
    public function testPropertyUnitRate()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "billable"
     */
    public function testPropertyBillable()
    {
    }

    /**
     * Test attribute "released"
     */
    public function testPropertyReleased()
    {
    }

    /**
     * Test attribute "allocated"
     */
    public function testPropertyAllocated()
    {
    }

    /**
     * Test attribute "billable_quantity"
     */
    public function testPropertyBillableQuantity()
    {
    }

    /**
     * Test attribute "financial_period"
     */
    public function testPropertyFinancialPeriod()
    {
    }

    /**
     * Test attribute "batch_nbr"
     */
    public function testPropertyBatchNbr()
    {
    }

    /**
     * Test attribute "use_billable_qty"
     */
    public function testPropertyUseBillableQty()
    {
    }

    /**
     * Test attribute "start_date"
     */
    public function testPropertyStartDate()
    {
    }

    /**
     * Test attribute "end_date"
     */
    public function testPropertyEndDate()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }

    /**
     * Test attribute "earning_type"
     */
    public function testPropertyEarningType()
    {
    }

    /**
     * Test attribute "overtime_multiplier"
     */
    public function testPropertyOvertimeMultiplier()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "project_task"
     */
    public function testPropertyProjectTask()
    {
    }

    /**
     * Test attribute "debit_account"
     */
    public function testPropertyDebitAccount()
    {
    }

    /**
     * Test attribute "debit_subaccount"
     */
    public function testPropertyDebitSubaccount()
    {
    }

    /**
     * Test attribute "credit_account"
     */
    public function testPropertyCreditAccount()
    {
    }

    /**
     * Test attribute "credit_subaccount"
     */
    public function testPropertyCreditSubaccount()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "employee"
     */
    public function testPropertyEmployee()
    {
    }

    /**
     * Test attribute "customer_vendor"
     */
    public function testPropertyCustomerVendor()
    {
    }

    /**
     * Test attribute "account_group"
     */
    public function testPropertyAccountGroup()
    {
    }

    /**
     * Test attribute "debit_account_group"
     */
    public function testPropertyDebitAccountGroup()
    {
    }

    /**
     * Test attribute "credit_account_group"
     */
    public function testPropertyCreditAccountGroup()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "error_info"
     */
    public function testPropertyErrorInfo()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
