<?php
/**
 * ProjectTransactionQueryParametersTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * ProjectTransactionQueryParametersTest Class Doc Comment
 *
 * @category    Class
 * @description ProjectTransactionQueryParameters
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProjectTransactionQueryParametersTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProjectTransactionQueryParameters"
     */
    public function testProjectTransactionQueryParameters()
    {
    }

    /**
     * Test attribute "module"
     */
    public function testPropertyModule()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "project"
     */
    public function testPropertyProject()
    {
    }

    /**
     * Test attribute "project_task"
     */
    public function testPropertyProjectTask()
    {
    }

    /**
     * Test attribute "billable"
     */
    public function testPropertyBillable()
    {
    }

    /**
     * Test attribute "branch"
     */
    public function testPropertyBranch()
    {
    }

    /**
     * Test attribute "date"
     */
    public function testPropertyDate()
    {
    }

    /**
     * Test attribute "from_period"
     */
    public function testPropertyFromPeriod()
    {
    }

    /**
     * Test attribute "to_period"
     */
    public function testPropertyToPeriod()
    {
    }

    /**
     * Test attribute "number_to_read"
     */
    public function testPropertyNumberToRead()
    {
    }

    /**
     * Test attribute "skip_records"
     */
    public function testPropertySkipRecords()
    {
    }

    /**
     * Test attribute "expand_note"
     */
    public function testPropertyExpandNote()
    {
    }

    /**
     * Test attribute "greater_than_value"
     */
    public function testPropertyGreaterThanValue()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }

    /**
     * Test attribute "last_modified_date_time_condition"
     */
    public function testPropertyLastModifiedDateTimeCondition()
    {
    }

    /**
     * Test attribute "created_date_time"
     */
    public function testPropertyCreatedDateTime()
    {
    }

    /**
     * Test attribute "created_date_time_condition"
     */
    public function testPropertyCreatedDateTimeCondition()
    {
    }

    /**
     * Test attribute "page_number"
     */
    public function testPropertyPageNumber()
    {
    }

    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {
    }
}
