<?php
/**
 * SupplierPOBalanceDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ekstralys\VismaNetApi;

/**
 * SupplierPOBalanceDtoTest Class Doc Comment
 *
 * @category    Class
 * @description SupplierPOBalanceDto
 * @package     Ekstralys\VismaNetApi
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SupplierPOBalanceDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SupplierPOBalanceDto"
     */
    public function testSupplierPOBalanceDto()
    {
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
    }

    /**
     * Test attribute "total_po_on_hold_order_total"
     */
    public function testPropertyTotalPoOnHoldOrderTotal()
    {
    }

    /**
     * Test attribute "total_po_on_hold_line_total"
     */
    public function testPropertyTotalPoOnHoldLineTotal()
    {
    }

    /**
     * Test attribute "total_open_po_order_total"
     */
    public function testPropertyTotalOpenPoOrderTotal()
    {
    }

    /**
     * Test attribute "total_open_po_line_total"
     */
    public function testPropertyTotalOpenPoLineTotal()
    {
    }

    /**
     * Test attribute "total_closed_po_order_total"
     */
    public function testPropertyTotalClosedPoOrderTotal()
    {
    }

    /**
     * Test attribute "total_closed_po_line_total"
     */
    public function testPropertyTotalClosedPoLineTotal()
    {
    }

    /**
     * Test attribute "last_modified_date_time"
     */
    public function testPropertyLastModifiedDateTime()
    {
    }
}
