<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ekstralys\VismaNetApi;

use \Ekstralys\VismaNetApi\Configuration;
use \Ekstralys\VismaNetApi\ApiException;
use \Ekstralys\VismaNetApi\ObjectSerializer;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for customerChangeCustomerNrActionByinternalId
     *
     * Updates the CustomerNr for the specified Customer.
     *
     */
    public function testCustomerChangeCustomerNrActionByinternalId()
    {
    }

    /**
     * Test case for customerCreateDunningLetterActionBycustomer
     *
     * Creates dunning letters for a specific customer.
     *
     */
    public function testCustomerCreateDunningLetterActionBycustomer()
    {
    }

    /**
     * Test case for customerGetAll
     *
     * Get a range of customers - ScreenId=AR303000.
     *
     */
    public function testCustomerGetAll()
    {
    }

    /**
     * Test case for customerGetAllCashSalesForCustomerBycustomerNumber
     *
     * Get a range of cash sales for a specific customer.
     *
     */
    public function testCustomerGetAllCashSalesForCustomerBycustomerNumber()
    {
    }

    /**
     * Test case for customerGetAllContactsForCustomerBycustomerCd
     *
     * Get a range of Contacts of a specific customer.
     *
     */
    public function testCustomerGetAllContactsForCustomerBycustomerCd()
    {
    }

    /**
     * Test case for customerGetAllCustomerBalance
     *
     * Get the balance for a range of customers.
     *
     */
    public function testCustomerGetAllCustomerBalance()
    {
    }

    /**
     * Test case for customerGetAllDocumentsForCustomerBycustomerNumber
     *
     * Gets a range of documents for a specific customer.
     *
     */
    public function testCustomerGetAllDocumentsForCustomerBycustomerNumber()
    {
    }

    /**
     * Test case for customerGetAllInvoicesForCustomerBycustomerNumber
     *
     * Get a range of invoices for a specific customer.
     *
     */
    public function testCustomerGetAllInvoicesForCustomerBycustomerNumber()
    {
    }

    /**
     * Test case for customerGetAllOrderForCustomerBycustomerCd
     *
     * Get a range of SO Orders of a specific customer.
     *
     */
    public function testCustomerGetAllOrderForCustomerBycustomerCd()
    {
    }

    /**
     * Test case for customerGetAllSalesOrderBasicForCustomerBycustomerCd
     *
     * Get a range of SO Orders Basic of a specific customer.
     *
     */
    public function testCustomerGetAllSalesOrderBasicForCustomerBycustomerCd()
    {
    }

    /**
     * Test case for customerGetBycustomerCd
     *
     * Get a specific customer.
     *
     */
    public function testCustomerGetBycustomerCd()
    {
    }

    /**
     * Test case for customerGetCustomerBalanceBycustomerCd
     *
     * Get a specific customer's balance - ScreenId=AR303000.
     *
     */
    public function testCustomerGetCustomerBalanceBycustomerCd()
    {
    }

    /**
     * Test case for customerGetCustomerClasses
     *
     * Get Customer Classes - ScreenId=AR201000.
     *
     */
    public function testCustomerGetCustomerClasses()
    {
    }

    /**
     * Test case for customerGetCustomerDirectDebitBycustomerCd
     *
     * Get direct debit information for a specific customer(only for Netherlands).
     *
     */
    public function testCustomerGetCustomerDirectDebitBycustomerCd()
    {
    }

    /**
     * Test case for customerGetCustomerNoteBycustomerCd
     *
     * Get a specific customer's note.
     *
     */
    public function testCustomerGetCustomerNoteBycustomerCd()
    {
    }

    /**
     * Test case for customerGetSalesPersonsForCustomerBycustomerCd
     *
     * Get a range of Sales Persons of a specific customer.
     *
     */
    public function testCustomerGetSalesPersonsForCustomerBycustomerCd()
    {
    }

    /**
     * Test case for customerGetSpecificCustomerClassBycustomerClassId
     *
     * Get a specific customer class - ScreenId=AR201000.
     *
     */
    public function testCustomerGetSpecificCustomerClassBycustomerClassId()
    {
    }

    /**
     * Test case for customerPost
     *
     * Creates a customer.
     *
     */
    public function testCustomerPost()
    {
    }

    /**
     * Test case for customerPutBycustomerCd
     *
     * Updates a specific customer.
     *
     */
    public function testCustomerPutBycustomerCd()
    {
    }
}
