<?php
/**
 * ExpenseReceiptApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Visma Net API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 8.43.00.1002
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ekstralys\VismaNetApi;

use \Ekstralys\VismaNetApi\Configuration;
use \Ekstralys\VismaNetApi\ApiException;
use \Ekstralys\VismaNetApi\ObjectSerializer;

/**
 * ExpenseReceiptApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ekstralys\VismaNetApi
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ExpenseReceiptApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for expenseReceiptCreateAttachmentByreceiptNumber
     *
     * Creates an attachment and associates it with an expense receipt. If the file already exists, a new revision is created..
     *
     */
    public function testExpenseReceiptCreateAttachmentByreceiptNumber()
    {
    }

    /**
     * Test case for expenseReceiptGetAll
     *
     * Get a range of Expense Receipts, a filter needs to be specified. ScreenId=EP301020.
     *
     */
    public function testExpenseReceiptGetAll()
    {
    }

    /**
     * Test case for expenseReceiptGetByreceiptNumber
     *
     * Get a specific ExpenseReceipt.
     *
     */
    public function testExpenseReceiptGetByreceiptNumber()
    {
    }

    /**
     * Test case for expenseReceiptPost
     *
     * Create a Expense Receipt.
     *
     */
    public function testExpenseReceiptPost()
    {
    }

    /**
     * Test case for expenseReceiptPutByreceiptNumber
     *
     * Update a Expense Receipt.
     *
     */
    public function testExpenseReceiptPutByreceiptNumber()
    {
    }
}
